language: python
python: "2.7"
services:
  - docker
jobs:
  include:
    - stage: build
      script: bash ./build.sh
    - stage: release
      script: bash ./build.sh api && bash ./release.sh

stages:
  - build
  - name: release
    if: type = push AND branch = master
